apiVersion: v1
kind: Service
metadata:
  name: {{ include "home-task.fullname" . }}
  namespace: {{ include "home-task.namespace" . }}
  labels:
    app: {{ include "home-task.name" . }}
    chart: {{ include "home-task.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    app: {{ include "home-task.name" . }}
  type: {{ .Values.service.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 5000