version: "3.12"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: home-task-revolut:latest
    ports: 
      - 80:5000
    restart: always
    networks:
      - webnet

networks:
  webnet:

