# Default values for home-task.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: "home-task"
fullnameOverride: "home-task"
namespace: "revolut"

replicaCount: 3

image:
  repository: joaomartins990/home-task-revolut
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "1.0.17"

podInitContainers:
  - command:
      - python3
      - -m 
      - unittest
      - -v
      - test_app.py
    image: joaomartins990/home-task-revolut
    name: init-tests-home-task
resources:
  limits:
    cpu: 256m
    memory: 500Mi
  requests:
    cpu: 150m
    memory: 256Mi

livenessProbe:
  enabled: true
  failureThreshold: 10
  timeoutSeconds: 5
  successThreshold: 1
  periodSeconds: 10
  initialDelaySeconds: 45

readinessProbe:
  enabled: true
  failureThreshold: 10
  timeoutSeconds: 5
  successThreshold: 1
  periodSeconds: 10
  initialDelaySeconds: 45

updateStrategy:
  type: RollingUpdate
  maxUnavailable: 25%

service:
  type: ClusterIP
  port: 80

podDisruptionBudget:
  maxUnavailable: 1
